development:
  adapter: postgresql
  database: ziecreative_development
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000
  reconnect: true
  host: localhost

test:
  adapter: postgresql
  database: ziecreative_test
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000
  reconnect: true
  host: localhost

production:
  adapter: postgresql
  database: ziecreative_production
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000
  reconnect: true
  host: localhost
